#!/usr/bin/env python3
"""Smoke/integration tests for the SiteBuilder build flow.

Scaffolds a throwaway site with ``manager.create_site``, adds one post, runs a
real build, and asserts the expected output is generated. No sample site ships
with the package. Network-reliant plugins (cppreference) and mermaid rendering
degrade to warnings, so this stays green offline/first-run.
"""

import tempfile
import unittest
from pathlib import Path

from pagesmith.builder import SiteBuilder
from pagesmith.manager import create_site


POST = """---
title: Hello World
date: 2026-09-22
author: Pagesmith
draft: false
---

# Hello World

This is a test post generated by the smoke test.
"""


class TestSiteBuilderSmoke(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory()
        cls.root = Path(cls.tmp.name).resolve()
        cls.site_dir = create_site('smoke', title='Smoke Site', base_dir=cls.root)
        posts = cls.site_dir / 'posts' / 'en'
        posts.mkdir(parents=True, exist_ok=True)
        (posts / '2026-09-22-hello-world.md').write_text(POST, encoding='utf-8')
        cls.output = cls.root / 'out'
        cls.builder = SiteBuilder(cls.site_dir, str(cls.output))
        cls.result = cls.builder.build()

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def test_managers_initialized(self):
        self.assertIsNotNone(self.builder.content_parser)
        self.assertIsNotNone(self.builder.url_manager)
        self.assertIsNotNone(self.builder.asset_manager)
        self.assertIsNotNone(self.builder.template_renderer)
        self.assertIsNotNone(self.builder.page_builder)
        self.assertIsNotNone(self.builder.taxonomy_manager)

    def test_config_loaded(self):
        self.assertIn('site', self.builder.config)
        self.assertIn('languages', self.builder.config)
        self.assertIn('pages', self.builder.config)
        self.assertIn('en', self.builder.languages)

    def test_build_succeeds(self):
        self.assertTrue(self.result)

    def test_output_files_generated(self):
        output = self.builder.output_dir
        self.assertTrue(output.exists())
        self.assertTrue((output / 'index.html').exists(), 'index.html not generated')
        self.assertTrue((output / 'feed.xml').exists(), 'feed.xml not generated')
        self.assertTrue((output / 'sitemap.xml').exists(), 'sitemap.xml not generated')
        self.assertIn('Smoke Site', (output / 'index.html').read_text(encoding='utf-8'))

    def test_non_default_language_generated(self):
        if 'pl' in self.builder.languages:
            self.assertTrue(
                (self.builder.output_dir / 'pl' / 'index.html').exists(),
                'pl/index.html not generated',
            )

    def test_section_pages_generated(self):
        output = self.builder.output_dir
        config = self.builder.config
        built = 0
        for page_name, page_config in config.get('pages', {}).items():
            markdown = page_config.get('markdown')
            if not (page_config.get('section') or markdown):
                continue
            slug = Path(markdown).stem if markdown else page_name
            self.assertTrue(
                (output / 'sections' / f'{slug}.html').exists(),
                f'sections/{slug}.html not generated',
            )
            built += 1
        self.assertGreater(built, 0, 'no section pages configured in scaffolded site')


if __name__ == '__main__':
    unittest.main()